title: Doodle detector
hero_image: images/banner.png
description: Train the computer to recognise what you have drawn
version: 1
listed: false
copyedit: false
last_tested: "2024-06-25"
steps:
  - title: What you will make
  - title: Set up the project
    completion:
    - engaged
  - title: Draw some examples
  - title: Train the model
  - title: Create a canvas
  - title: What was it?
    completion:
    - internal
  - title: Challenge
    challenge: true
  - title: What can you do now?
    completion:
    - external
