title: Doodle Detector
hero_image: images/banner.png
description: Train the computer to recognise what you have drawn
version: 1
listed: false
copyedit: false
last_tested: "2024-06-25"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
  - title: Introduction
  - title: Step title
  - title: What next?
  - title: Introduction

