---
title: Détecteur de gribouillages
hero_image: images/banner.png
description: Entraîne l'ordinateur à reconnaître ce que tu as dessiné
version: 1
listed: true
copyedit: false
last_tested: "2024-06-25"
steps:
  - title: Ce que tu vas faire
  - title: Configurer le projet
    completion:
    - engaged
  - title: Dessiner quelques exemples
  - title: Entraîner le modèle
  - title: Créer un canvas
  - title: C'était quoi ?
    completion:
    - internal
  - title: Défi
    challenge: true
    completion:
    - external