title: Doodle detector
hero_image: images/banner.png
description: Train the computer to recognise what you have drawn
version: 1
listed: true
copyedit: false
last_tested: "2024-06-25"
steps:
  - title: Ce que tu vas faire
  - title: Configurer le projet
    completion:
    - engaged
  - title: Draw some examples
  - title: Entraîner le modèle
  - title: Create a canvas
  - title: What was it?
    completion:
    - internal
  - title: Défi
    challenge: true
  - title: Que peux-tu faire maintenant ?
    completion:
    - external
